### ISSUE TITLE
Can the Networkmaps support the SSO with the Keycloak

### ISSUE THREAD

**Issue by jj1682000** [pablomarle/networkmaps#10]
[Keycloak](https://www.keycloak.org/)

**Comment by pablomarle** [comment]
As of now, it is not supported.
What I can do is add support for either OpenID or SAML authentication. I'll add it to my To Do list.

**Comment by jj1682000** [comment]
> What I can do is add support for either OpenID or SAML authentication.

Awesome!
Thank you so much!

**Comment by pablomarle** [comment]
So, I've pushed some code to add initial support for OpenId authentication. 
To configure NetworkMaps to use it, on the users section of the configuration, you have to configure the following:
_"users": {
        "authentication": "openid",
        "openid": {
            "client_id": "<client id provided by openid provider>",
            "auth_server_url": "<openid provider base url>",
            "secret": "<secret (only needed if realm not public)>"
        },
}_

It will use the Authorization Code Flow, and as authentication, it can use only the "client_secret_post".
It requires the email and profile scopes (to get email address of users as well as name and family_name).

I've tested this with a Keycloak deployment. I'll test it later with Google.

I'll also update the documentation in a few hours.

Please, let me know if this works for you.

Regards,

**Comment by jj1682000** [comment]
> So, I've pushed some code to add initial support for OpenId authentication.
> To configure NetworkMaps to use it, on the users section of the configuration, you have to configure the following:
> 
> ```
> "users": {
>     "authentication": "openid",
>     "openid": {
>         "client_id": "<client id provided by openid provider>",
>         "auth_server_url": "<openid provider base url>",
>         "secret": "<secret (only needed if realm not public)>"
>     },
> }
> ```
> 
> It will use the Authorization Code Flow, and as authentication, it can use only the "client_secret_post".
> It requires the email and profile scopes (to get email address of users as well as name and family_name).
> 
> I've tested this with a Keycloak deployment. I'll test it later with Google.
> 
> I'll also update the documentation in a few hours.
> 
> Please, let me know if this works for you.
> 
> Regards,

Thank you so much! 
I'll test this new code in my environment.
Of cause, I'll tell you if this works for me or there are any problems. 

Regards,

**Comment by jj1682000** [comment]
awesome!
