### ISSUE TITLE
Does not appear to use Config.json's socket.address & port.

### ISSUE THREAD

**Issue by wcrisman** [pablomarle/networkmaps#11]
The browser is attempting to load resources from localhost:3000 even though I have setup a config.json file with my server's ip & port.  Of course this fails since it isn't localhost:3000.  I know it reads the config.json file given the nginx log is not showing that error (the first problem I ran into).  

I had a similar problem with the /var/libs/xxx folders which I tried to redirect to another location, but I gave up and placed the folders in the default locations.  Unfortunately I cannot do that with the server its self.

Running NodeJS 13.13.0 using Nginx & Phusion Passenger.  No SSL or anything else fancy.

**Comment by wcrisman** [comment]
{
    "socket": {
        "address": "10.18.16.62",
        "port": 80
    },
    "sendmail": {
        "server": "xxxxxxxxx",
        "port": 25,
        "is_secured": false,
        "user": "xxxxx",
        "password": "xxxxxxxx",
        "from": "xxxxxxxxx"
    }
}

**Comment by wcrisman** [comment]
Chrome browser console output:
networkmaps.avpanthers.org/:1 GET http://localhost:3000/static/css/index.css net::ERR_CONNECTION_REFUSED
networkmaps.avpanthers.org/:1 GET http://localhost:3000/static/css/index.css net::ERR_CONNECTION_REFUSED
networkmaps.avpanthers.org/:1 GET http://localhost:3000/static/css/index.css net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for chrome-extension://hcobdfnjjaceclfdjpmmpiknimccjpmf/content_script.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://bpcagekijmfcocgjlnnhpdogbplajjfn/lib/jquery.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
(index):1 Uncaught ReferenceError: main is not defined
    at onload ((index):1)
onload @ (index):1

**Comment by pablomarle** [comment]
Hello,

can you add the logs from the server itself showing what happens when you start the server and when your client sends the request?

Thanks,
Pablo.

**Comment by pablomarle** [comment]
Closed due to lack of response.
