### ISSUE TITLE
ERR_UNKNOWN_ENCODING

### ISSUE THREAD

**Issue by jj1682000** [pablomarle/networkmaps#12]
./server.js

`---
REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
WS /user HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 COOKIE:NetSessionNoSec=7aae71f1a5fc62b54acb16dc83df24db4a43102705367b7bdb351fe347ca94a3 REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
node:internal/streams/writable:303
      throw new ERR_UNKNOWN_ENCODING(encoding);
      ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: true
    at new NodeError (node:internal/errors:278:15)
    at Socket.Writable.write (node:internal/streams/writable:303:13)
    at Sender.sendFrame (/home/centos/networkmaps-master/node_modules/ws/lib/sender.js:397:20)
    at Sender.doPing (/home/centos/networkmaps-master/node_modules/ws/lib/sender.js:188:10)
    at Sender.ping (/home/centos/networkmaps-master/node_modules/ws/lib/sender.js:174:12)
    at WebSocket.ping (/home/centos/networkmaps-master/node_modules/ws/lib/websocket.js:282:18)
    at Timeout._onTimeout (/home/centos/networkmaps-master/lib/ws.js:477:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  code: 'ERR_UNKNOWN_ENCODING'
}
--`

$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

run networkmaps on Centos8

$ node --version
v15.5.1

**Comment by jj1682000** [comment]
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by pablomarle** [comment]
Hello. Thanks for reporting the problem.

When does the issue appear? Have you found a way to replicate it?

Thanks,

**Comment by jj1682000** [comment]
Yes, I have found a way to replicate it.

The issue does not appear when there is no browser to open the URL(http://10.232.2.13:3000/)
======begin========
[centos@networkmaps networkmaps-master]$ ./server.js --config config.json
Config file read from (config.json)
Configuration file read.

If you like NetworkMaps, consider making a small donation :)

Server running at http://10.232.2.13:3000/
======end=========

But when I use browser to open the URL, the issue appear.
======begin==========
[centos@networkmaps networkmaps-master]$ ./server.js --config config.json
Config file read from (config.json)
Configuration file read.

If you like NetworkMaps, consider making a small donation :)

Server running at http://10.232.2.13:3000/
Saving UserMGT data
UserMGT data saved
GET / HOST:10.232.2.13:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
GET /static/css/index.css HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
GET /static/js/index.js HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
GET /static/js/DOM.js HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
GET /favicon.ico HOST:10.232.2.13:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:NetSessionNoSec=c691acc8e15b7eeb19e67482b0299a516189e7cca1ae9555629634f43b8087f6 REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
WS /user HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
GET /static/img/sample1.png HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
GET /static/img/icon.png HOST:networkmaps.cefinity.com:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 COOKIE:undefined REMOTEIP:::ffff:10.88.21.253 XFORWARDED:undefined
node:internal/streams/writable:303
      throw new ERR_UNKNOWN_ENCODING(encoding);
      ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: true
    at new NodeError (node:internal/errors:278:15)
    at Socket.Writable.write (node:internal/streams/writable:303:13)
    at Sender.sendFrame (/home/centos/networkmaps-master/node_modules/ws/lib/sender.js:397:20)
    at Sender.doPing (/home/centos/networkmaps-master/node_modules/ws/lib/sender.js:188:10)
    at Sender.ping (/home/centos/networkmaps-master/node_modules/ws/lib/sender.js:174:12)
    at WebSocket.ping (/home/centos/networkmaps-master/node_modules/ws/lib/websocket.js:282:18)
    at Timeout._onTimeout (/home/centos/networkmaps-master/lib/ws.js:477:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  code: 'ERR_UNKNOWN_ENCODING'
}
[centos@networkmaps networkmaps-master]$
======end===========

**Comment by DerTFL** [comment]
Hello! I have the same problem, but on AlpineLinux.

**Comment by pablomarle** [comment]
So, I finally managed to reproduce the issue. It seems to appear only when using node version 15.

When calling ws.ping, incorrect parameters were passed. This didn't seem to cause any problem on node v14 or lower. But on node v15, the incorrect parameters were passed to socket.write as the encoding.

It should be fixed on my latest push.

Thanks for reporting the problem.

**Comment by jj1682000** [comment]
awesome!
