### ISSUE TITLE
account confirmation not found

### ISSUE THREAD

**Issue by rapierbit** [pablomarle/networkmaps#13]
Procedure using macOS Mojave, Safari or Firefox :

Go to https://www.networkmaps.org
Click Try It Now
Click Register
Add name and e-mail
Click "Register"
Receive e-mail with validation link
Click validation link
Go to web page that says "Not Found"
Try Registering again
Receive message that says "Email already registered"

Is this software EOL?

**Comment by pablomarle** [comment]
Hello.

The software is not EoL.
Can you send me an email (with your email address :) )  so I can check what happened with your registration email?

My email address: pablo@networkmaps.org

Thanks,
Pablo.

**Comment by pablomarle** [comment]
I'm closing this issue as this doesn't seem to be a problem of the software itself, but of the implementation.
Please,  contact me with the details requested if the issue persist.

Thanks,
Pablo.
