### ISSUE TITLE
can't create networkmaps

### ISSUE THREAD

**Issue by ndroftheline** [pablomarle/networkmaps#18]
https://app.networkmaps.org/ doesn't have any new diagram button or list of existing buttons. There doesn't appear to be any way to use the software.

This is the same behaviour as a self-hosted version running ubuntu 20.04 and node 16. 

have tried on latest chrome, firefox, and edge in both standard and incognito windows. 

what am i doing wrong?

**Comment by pablomarle** [comment]
Hello.

To be able to create diagrams, first you have to create your account. This is done using the register button. Follow the process and once you have logged into your account, you should see the button to create diagrams (New Diagram).

Let me know if this helps or not. If not, can you share a screenshot of what you are seeing?

Thanks,
Pablo.

**Comment by pablomarle** [comment]
Closing due to lack of response.
