### ISSUE TITLE
Blank screen after successful installation

### ISSUE THREAD

**Issue by tmanok** [pablomarle/networkmaps#19]
After successful installation, the server only supplies a blank page when a client attempts to access it using the correct port and hostname.

1. Clone the main repository
2. Create a user for network maps
3. Chown -R user:user /path/to/networkmaps/
4. Create /var/lib/networkmaps (and all sub dirs)
5. Chown -R user:user /var/lib/networkmaps/
6. Edit the configuration accordingly
7. /path/to/networkmaps/server.js (verify there are no errors)

I'm expecting the software to bring up a login screen, but instead a completely empty page appears.

 - OS: Tried Windows Server 2016 and Linux Mint 19.2
 - Browser Google Chrome - latest

This is the most basic I can describe the issue, however for more details, here is my configuration file with censored credentials:
```
{
    "socket": {
        "address": "192.168.60.127",
        "port": 3000
    },
    "sendmail": {
        "server": "*******************",
        "port": 587,
        "is_secured": true,
        "user": "*********",
        "password": "**********",
        "from": "***********"
    },
    "users": {
        "admin_username": "admin",
        "admin_password": "**********"
    }
}
```
I've noticed in the "Preview" of my comment that the configuration file looks flat, it is not and I have tested it with json lint. 
Thanks!

**Comment by pablomarle** [comment]
Hello.

Thanks for reporting the issue.

Can you provide the url your client is trying to access? Is it http://192.168.60.127:3000 or are you trying to access it by hostname?

Also, can you provide the source code (html) of the blank page he is getting?

Regards,
Pablo.

**Comment by tmanok** [comment]
Hi Pablo!

Sorry I didn't see the notification for this. I was indeed connecting to http://192.168.60.127:3000/, the HTML looks like this:
https://imgur.com/a/st2PJNd Sorry I had to use VNC to access a machine on the network quickly I can copy and paste the direct code tomorrow. 
Thank you for your time!

**Comment by pablomarle** [comment]
Thanks for your response. Can you also check one more thing?
In the console of your browser (you can access it via dev tools CTRL+SHIFT+J), can you check if you have any error?

And also, can you paste the logs from the server.

**Comment by tmanok** [comment]
Browser console errors:
https://imgur.com/a/k3jGIt2

Systemctl status networkmaps.service errors:
```
* networkmaps.service - NetworkMaps Web Server
   Loaded: loaded (/etc/systemd/system/networkmaps.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-08-17 22:55:12 PDT; 12h ago
 Main PID: 121 (node)
    Tasks: 12 (limit: 57655)
   Memory: 54.3M
      CPU: 679ms
   CGroup: /system.slice/networkmaps.service
           `-121 /usr/bin/node /opt/networkmaps/server.js --config /opt/networkmaps/config.json

Aug 18 11:16:11 NetworkMaps node[121]: GET /static/js/index.js HOST:192.168.60.127:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like G
Aug 18 11:16:11 NetworkMaps node[121]: 404
Aug 18 11:16:12 NetworkMaps node[121]: GET /static/js/DOM.js HOST:192.168.60.127:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gec
Aug 18 11:16:12 NetworkMaps node[121]: 404
Aug 18 11:16:12 NetworkMaps node[121]: GET /static/js/index.js HOST:192.168.60.127:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like G
Aug 18 11:16:12 NetworkMaps node[121]: 404
Aug 18 11:16:13 NetworkMaps node[121]: GET /favicon.ico HOST:192.168.60.127:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) C
Aug 18 11:16:13 NetworkMaps node[121]: 404
Aug 18 11:17:00 NetworkMaps node[121]: GET /static/css/index.css HOST:192.168.60.127:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Aug 18 11:17:00 NetworkMaps node[121]: 404
```

Systemd Service File:
```
[Unit]
Description=NetworkMaps Web Server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=on-failure
RestartSec=1
User=networkmaps
ExecStart=/usr/bin/node /opt/networkmaps/server.js --config /opt/networkmaps/config.json

[Install]
WantedBy=multi-user.target
```

All files on the server relating to network maps:
root@NetworkMaps:~# find / -type d -name "networkmaps" 2> /dev/null
/var/lib/networkmaps
/etc/networkmaps
/home/networkmaps
/opt/networkmaps

Owners in each of those directories are recursively the user "networkmaps". (Chown -R networkmaps:networkmaps to each was performed on multiple occasions). 

Thanks!

**Comment by pablomarle** [comment]
```
Aug 18 11:16:11 NetworkMaps node[121]: GET /static/js/index.js HOST:192.168.60.127:3000 USER AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like G
Aug 18 11:16:11 NetworkMaps node[121]: 404
```
These log entries are telling me that the server is unable to find the static files.
On the systemd service file can you try to add the following entry under the [Service] section:
`WorkingDirectory=/opt/networkmaps`

This should be enough for the server to be able to find the static files (these files should be on /opt/networkmaps/html/static).

Let me know if this fixes your issue.

**Comment by tmanok** [comment]
Well that was incredibly embarassing. For some reason my logic was that NetworkMaps would already know its working directory because of its launch location. 

Thanks Pablo that worked like a charm! I appreciate your time and support with this issue, sorry it was so simple. 
Additionally, I'd like to thank you for investing so much time into developing this project and MaSSHandra which I still use on a number of workstations!


Tmanok
