### ISSUE TITLE
Sources for MaSSHandra?

### ISSUE THREAD

**Issue by abitrolly** [pablomarle/networkmaps#6]
I've [heard ](https://askubuntu.com/a/267120) that MaSSHandra had autodiscovery feature. Seems very useful if it pairs it with automatic layout algorithm. However, I couldn't find the source code. Is it available?

**Comment by pablomarle** [comment]
Hello.
MaSSHandra has autodiscovery features but I'm afraid MaSSHandra is not opensource.

I'll add in the future autodiscovery functions to NetworkMaps.
