### ISSUE TITLE
API to draw diagram

### ISSUE THREAD

**Issue by leslie-qiwa** [pablomarle/networkmaps#7]
**Is your feature request related to a problem? Please describe.**
As a dev-ops, I want to draw the diagram automatically. For example, when one switch or one node is added, I want to automatically update corresponding diagrams.

**Describe the solution you'd like**
I can use any network discovery tool or integrate with inventory system to get notified when new network device is identified, then I can call API to update diagrams. Thus people can always get real time view. 

**Describe alternatives you've considered**
do it by our own. but I do like the simplicity of this software and think it achieves our network topology purpose.

**Additional context**
Also, is there one specification about the diagram store format? maybe we can manipulate the diagram source file to achieve the purpose.

**Comment by pablomarle** [comment]
You can use this library if you want to update programatically your diagrams.
https://github.com/pablomarle/networkmaps/blob/master/networkmapslib.js

If you are not going to use javascript (which I can imagine), you can use it as a base to understand how the api works.
I'll try to add some more extensive documentation on how to use the api.
