### ISSUE TITLE
Initial startup issues

### ISSUE THREAD

**Issue by oshybrid** [pablomarle/networkmaps#8]
I had a couple of issues.  I tried to browse to it both locally on the server, and remotely from another PC (MAC) on the same network.

1). Even when I put in the config file a different port number it keeps trying to bringing the server up as 3000.  I made sure the spelling of the file and its location and that the CHMOD was 777.  I was using wiki.js at 3000 already.  I had to shut that program down in order to launch ./server.js.

The server output is as follows

/etc/networkmaps/networkmaps$ ./server.js
Config file read from default (/etc/networkmaps/config.json)
Use '--config <path_to_cfg_json>' to change config file location.
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at new HTTPServer (/etc/networkmaps/networkmaps/lib/httpserver.js:97:21)
    at main (/etc/networkmaps/networkmaps/server.js:457:17)
    at Object.<anonymous> (/etc/networkmaps/networkmaps/server.js:460:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Emitted 'error' event at:
    at Server.WebSocketServer._ultron.on (/etc/networkmaps/networkmaps/node_modules/ws/lib/WebSocketServer.js:84:46)
    at Server.emit (events.js:198:13)
    at emitErrorNT (net.js:1307:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

2) When I try to browse to the server IP and port (3000), every browser I try to use complains about that Web Socket are not allowed on the browser.  Even though wiki.js uses them without issue.  I tried http and https.

The output of the server is the following:

/etc/networkmaps/networkmaps$ ./server.js
Config file read from default (/etc/networkmaps/config.json)
Use '--config <path_to_cfg_json>' to change config file location.
Server running at http://localhost:3000/
GET / HOST:10.195.35.90:3000 USER AGENT:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 COOKIE:NetSessionNoSec=34777481f7a3554ff866477e8312485cf0dd17b9d54215046976a96fe0e11714; jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJicmFkLmh1dGNoaW5zQHppcGx5LmNvbSIsIm5hbWUiOiJBZG1pbmlzdHJhdG9yIiwiYXYiOm51bGwsInR6IjoiQW1lcmljYS9OZXdfWW9yayIsImxjIjoiZW4iLCJkZiI6IiIsImFwIjoiIiwicGVybWlzc2lvbnMiOlsibWFuYWdlOnN5c3RlbSJdLCJncm91cHMiOlsxXSwiaWF0IjoxNjAwNTM3MjEzLCJleHAiOjE2MDA1MzkwMTMsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.lgxAPKgGW8XWqbjTSPEwOxNZQf_9eZb4vc_8AoXBID5hAYetJdIrW84XU25CLjzHvxmG18z6GcfrFuSMXMw_TGmnDE9ak-7z7wGJKomaIOJvF92EOqisnZ2YGYc_MuORKp15pmrOSDusXQ89puw8qed070AYRsHlUiiQoniA-ol8p8zB2Yd4L1l2jSUUwDmyOcIs-23GSXvXyejbbNjgQXYaQ-zhd_50Zt2Bg1sM-bm0O6GnRau3On-onLb9NthMxcTpIEM7u87JaIn9riAlY3KR1gtl7L6XjI8OEcMxLdoEEAmx6sQ3jTBFhhhgfwzGHLMOAMUNhC4n8pSAZFc_Ng REMOTEIP:::ffff:10.195.35.53 XFORWARDED:undefined
GET /favicon.ico HOST:10.195.35.90:3000 USER AGENT:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 COOKIE:NetSessionNoSec=34777481f7a3554ff866477e8312485cf0dd17b9d54215046976a96fe0e11714; jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJicmFkLmh1dGNoaW5zQHppcGx5LmNvbSIsIm5hbWUiOiJBZG1pbmlzdHJhdG9yIiwiYXYiOm51bGwsInR6IjoiQW1lcmljYS9OZXdfWW9yayIsImxjIjoiZW4iLCJkZiI6IiIsImFwIjoiIiwicGVybWlzc2lvbnMiOlsibWFuYWdlOnN5c3RlbSJdLCJncm91cHMiOlsxXSwiaWF0IjoxNjAwNTM3MjEzLCJleHAiOjE2MDA1MzkwMTMsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.lgxAPKgGW8XWqbjTSPEwOxNZQf_9eZb4vc_8AoXBID5hAYetJdIrW84XU25CLjzHvxmG18z6GcfrFuSMXMw_TGmnDE9ak-7z7wGJKomaIOJvF92EOqisnZ2YGYc_MuORKp15pmrOSDusXQ89puw8qed070AYRsHlUiiQoniA-ol8p8zB2Yd4L1l2jSUUwDmyOcIs-23GSXvXyejbbNjgQXYaQ-zhd_50Zt2Bg1sM-bm0O6GnRau3On-onLb9NthMxcTpIEM7u87JaIn9riAlY3KR1gtl7L6XjI8OEcMxLdoEEAmx6sQ3jTBFhhhgfwzGHLMOAMUNhC4n8pSAZFc_Ng REMOTEIP:::ffff:10.195.35.53 XFORWARDED:undefined
GET / HOST:10.195.35.90:3000 USER AGENT:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 COOKIE:NetSessionNoSec=34777481f7a3554ff866477e8312485cf0dd17b9d54215046976a96fe0e11714; jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJicmFkLmh1dGNoaW5zQHppcGx5LmNvbSIsIm5hbWUiOiJBZG1pbmlzdHJhdG9yIiwiYXYiOm51bGwsInR6IjoiQW1lcmljYS9OZXdfWW9yayIsImxjIjoiZW4iLCJkZiI6IiIsImFwIjoiIiwicGVybWlzc2lvbnMiOlsibWFuYWdlOnN5c3RlbSJdLCJncm91cHMiOlsxXSwiaWF0IjoxNjAwNTM3MjEzLCJleHAiOjE2MDA1MzkwMTMsImF1ZCI6InVybjp3aWtpLmpzIiwiaXNzIjoidXJuOndpa2kuanMifQ.lgxAPKgGW8XWqbjTSPEwOxNZQf_9eZb4vc_8AoXBID5hAYetJdIrW84XU25CLjzHvxmG18z6GcfrFuSMXMw_TGmnDE9ak-7z7wGJKomaIOJvF92EOqisnZ2YGYc_MuORKp15pmrOSDusXQ89puw8qed070AYRsHlUiiQoniA-ol8p8zB2Yd4L1l2jSUUwDmyOcIs-23GSXvXyejbbNjgQXYaQ-zhd_50Zt2Bg1sM-bm0O6GnRau3On-onLb9NthMxcTpIEM7u87JaIn9riAlY3KR1gtl7L6XjI8OEcMxLdoEEAmx6sQ3jTBFhhhgfwzGHLMOAMUNhC4n8pSAZFc_Ng REMOTEIP:::ffff:10.195.35.53 XFORWARDED:undefined
Saving UserMGT data
UserMGT data saved
^C

/etc/networkmaps/networkmaps$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

![Capto_Capture 2020-09-19_11-07-33_AM](https://user-images.githubusercontent.com/44711163/93686143-1c358100-fa69-11ea-9700-7ab3f8bbd6bd.png)

![Capto_Capture 2020-09-19_10-38-30_AM](https://user-images.githubusercontent.com/44711163/93686118-03c56680-fa69-11ea-982d-28fccc1656fe.png)

**Comment by pablomarle** [comment]
Most likely reason for this issue is that there was an error reading the config file (maybe the file is not a valid json?). When this happens the application will use default settings (localhost port 3000). This explains the two issues you are having.
On the latest version I've added logging in case reading the config file fails. Can you try to get the latest version and run it again to see if an error message appears?
