### ISSUE TITLE
Add device programmatically does not set "Subtype" element

### ISSUE THREAD

**Issue by luis-palacios-palomino** [pablomarle/networkmaps#9]
The method "add_device(st, px, py, pz, sx, sy, sz, rx, ry, rz, color1, color2, base, callback)" of class "Diagram" (file networkmapslib.js) create the device but not assign the "Subtype":
"Server", :  "ADSR",  
"Storage",:  "ADST",  
"DB",     :  "AD_SDB",
"Web",    :  "AD_SW", 
"Mail",   :  "AD_SM", 
"DNS",    :  "AD_SD", 
"Log",    :  "AD_SL", 
"MemDB",  :  "AD_SC", 
"LDAP",   :  "AD_SA", 
"Robot",  :  "AD_SR", 
"Monitor",:  "AD_SMM",
"V.Guest",:  "AD_SVG",
"V.Host", :  "AD_SVH",
"GPU",    :  "AD_SN", 
"Windows",:  "AD_SOW",
"Linux",  :  "AD_SOL",
"Mac",    :  "AD_SOM",

Example:
// data.i: base id
diagram.add_device("AD_SD", 7, 0, 3, 1,1,1, 0,0,0, 6724044, 3368601, data.i, (error, data) => {
   console.log("device:", data);
   if(error) {
      console.log('error 2', error);
      exit();
   };});

Does not create the 3d image of "DNS server", it creates a "Cube 3d image".
![diagram](https://user-images.githubusercontent.com/23037804/96462627-0fea4280-1226-11eb-86d6-23e5208fcba1.png)

**Comment by pablomarle** [comment]
Hello Luis.

When using the API, the subtype of a device should not have the "AD" part. So:
"Server", :  "SR",  
"Storage",:  "ST",  
"DB",     :  "_SDB",
"Web",    :  "_SW",
"Mail",   :  "_SM",
"DNS",    :  "_SD",
"Log",    :  "_SL",
"MemDB",  :  "_SC",
"LDAP",   :  "_SA",
"Robot",  :  "_SR",
"Monitor",:  "_SMM",
"V.Guest",:  "_SVG",
"V.Host", :  "_SVH",
"GPU",    :  "_SN",
"Windows",:  "_SOW",
"Linux",  :  "_SOL",
"Mac",    :  "_SOM",

I'll try to expand the documentation of the api and library.
Let me know if this fixes the issue.

Regards,
Pablo.
